# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosql', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosql',
            name='current_release',
            field=models.CharField(default='Not found', max_length=100),
        ),
        migrations.AddField(
            model_name='nosql',
            name='data_url',
            field=models.URLField(default='Not found'),
        ),
        migrations.AddField(
            model_name='nosql',
            name='developer',
            field=models.CharField(default='Not found', max_length=100),
        ),
        migrations.AddField(
            model_name='nosql',
            name='implementation_language',
            field=models.CharField(default='Not found', max_length=60),
        ),
        migrations.AddField(
            model_name='nosql',
            name='initial_release',
            field=models.CharField(default='Not found', max_length=100),
        ),
        migrations.AddField(
            model_name='nosql',
            name='license',
            field=models.CharField(default='Not found', max_length=60),
        ),
        migrations.AddField(
            model_name='nosql',
            name='operating_systems',
            field=models.CharField(default='Not found', max_length=200),
        ),
        migrations.AddField(
            model_name='nosql',
            name='supported_programming',
            field=models.CharField(default='Not found', max_length=400),
        ),
        migrations.AddField(
            model_name='nosql',
            name='typing',
            field=models.CharField(default='Not found', max_length=200),
        ),
    ]
