# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nosql', '0002_auto_20161118_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.CharField(db_index=True, max_length=100)),
                ('commercial_type', models.BooleanField(default=False)),
                ('open_source_type', models.BooleanField(default=False)),
                ('free_type', models.BooleanField(default=False)),
                ('undefined_type', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.CharField(db_index=True, max_length=100)),
                ('amount_repos', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'Official driver'), (2, 'Community supported driver'), (3, 'Innoficial driver'), (0, 'Undefined status')], default=0)),
            ],
            options={
                'verbose_name': 'programming language',
                'verbose_name_plural': 'programming languages',
                'ordering': ('-amount_repos',),
            },
        ),
        migrations.RemoveField(
            model_name='nosql',
            name='license',
        ),
        migrations.RemoveField(
            model_name='nosql',
            name='supported_programming',
        ),
        migrations.AddField(
            model_name='programminglanguage',
            name='nosql',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programming_languages', to='nosql.Nosql'),
        ),
        migrations.AddField(
            model_name='license',
            name='nosql',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='nosql.Nosql'),
        ),
    ]
