# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nosql', '0003_auto_20161119_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='nosql',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='nosql.Nosql'),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='nosql',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programming_languages', to='nosql.Nosql'),
        ),
    ]
