# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosql', '0005_auto_20161121_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosql',
            name='amount_repos',
            field=models.IntegerField(default=0),
        ),
    ]
