# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosql', '0006_nosql_amount_repos'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosql',
            name='stackshare_votes',
            field=models.IntegerField(default=0),
        ),
    ]
