# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosql', '0007_nosql_stackshare_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosql',
            name='amount_stackoverflow_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nosql',
            name='stackoverflow_followers',
            field=models.IntegerField(default=0),
        ),
    ]
