# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nosql', '0008_auto_20161122_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('url', models.URLField()),
                ('number_backlinks', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-number_backlinks',),
            },
        ),
        migrations.AlterModelOptions(
            name='nosql',
            options={'ordering': ('-stackoverflow_followers',)},
        ),
        migrations.AddField(
            model_name='link',
            name='nosql',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='nosql.Nosql'),
        ),
    ]
