# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nosql', '0009_auto_20161129_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('positive', models.BooleanField(default=False)),
                ('probability', models.FloatField(default=0.0)),
                ('nosql', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='nosql.Nosql')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
