# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosql', '0010_auto_20161129_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='url',
            field=models.URLField(default='undefined', unique=True),
            preserve_default=False,
        ),
    ]
